### ISSUE TITLE
a crash, would you like to fix it ?

### ISSUE THREAD

**Issue by GaoZhenGit** [trojan-gfw/igniter#117]
I using your latest code to compile, on master branch. After connect to server successfully, I stop the client manually. Then it crash, here's the log below. By the way, would you like to release the latest apk that base on the latest code?
```
2020-03-12 18:33:26.380 29394-29428/? A/libc: Fatal signal 6 (SIGABRT), code -6 (SI_TKILL) in tid 29428 (jan_gfw.igniter), pid 29394 (jan_gfw.igniter)
2020-03-12 18:33:22.481 1435-1566/? E/BatteryExternalStatsWorker: no controller energy info supplied for bluetooth
2020-03-12 18:33:26.601 30001-30001/? A/DEBUG: *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
2020-03-12 18:33:26.601 30001-30001/? A/DEBUG: Build fingerprint: 'Xiaomi/cepheus/cepheus:9/PKQ1.181121.001/V10.2.35.0.PFACNXM:user/release-keys'
2020-03-12 18:33:26.601 30001-30001/? A/DEBUG: Revision: '0'
2020-03-12 18:33:26.601 30001-30001/? A/DEBUG: ABI: 'arm64'
2020-03-12 18:33:26.601 30001-30001/? A/DEBUG: pid: 29394, tid: 29428, name: jan_gfw.igniter  >>> io.github.trojan_gfw.igniter <<<
2020-03-12 18:33:26.601 30001-30001/? A/DEBUG: signal 6 (SIGABRT), code -6 (SI_TKILL), fault addr --------
2020-03-12 18:33:26.601 30001-30001/? A/DEBUG:     x0  0000000000000000  x1  00000000000072f4  x2  0000000000000006  x3  0000000000000008
2020-03-12 18:33:26.601 30001-30001/? A/DEBUG:     x4  0000000000000001  x5  00000070700d0f08  x6  000000000000003f  x7  0000000000000030
2020-03-12 18:33:26.601 30001-30001/? A/DEBUG:     x8  0000000000000083  x9  000000000000008e  x10 000000000000000c  x11 000000707051b6d4
2020-03-12 18:33:26.601 30001-30001/? A/DEBUG:     x12 0000000000000000  x13 0000000000000000  x14 0000000000000000  x15 0000000000000001
2020-03-12 18:33:26.601 30001-30001/? A/DEBUG:     x16 000000706fdbb4b3  x17 000000706fdbb4b0  x18 0000000000000000  x19 00000000000072d2
2020-03-12 18:33:26.601 30001-30001/? A/DEBUG:     x20 000000706fb41f60  x21 0000007070572bc0  x22 000000000000005a  x23 000000707059dbd5
2020-03-12 18:33:26.601 30001-30001/? A/DEBUG:     x24 0000007070570d40  x25 0000000000000018  x26 0000004000328c68  x27 00000000000001b0
2020-03-12 18:33:26.601 30001-30001/? A/DEBUG:     x28 00000040002a1200  x29 0000000000000000
2020-03-12 18:33:26.601 30001-30001/? A/DEBUG:     sp  0000004000328c10  lr  000000706fda35d0  pc  000000706fdbc218
2020-03-12 18:33:26.602 30001-30001/? A/DEBUG: backtrace:
2020-03-12 18:33:26.602 30001-30001/? A/DEBUG:     #00 pc 0000000000279218  /data/app/io.github.trojan_gfw.igniter-5rAl1hP3Mt63eBaNZgcPQA==/lib/arm64/libgojni.so
2020-03-12 18:33:26.856 30001-30001/? E/crash_dump64: cannot open libmiuindbg.so: No such file or directory
2020-03-12 18:33:26.863 1000-1000/? E//system/bin/tombstoned: Tombstone written to: /data/tombstones/tombstone_00
2020-03-12 18:33:26.976 28359-28411/? E/chromium: [ERROR:ssl_client_socket_impl.cc(1013)] handshake failed; returned -1, SSL error code 1, net_error -103
2020-03-12 18:33:26.977 30577-30704/? E/MSF.D.MonitorSocket: SocketException!
    java.net.SocketException: Software caused connection abort
        at java.net.SocketInputStream.socketRead0(Native Method)
        at java.net.SocketInputStream.socketRead(SocketInputStream.java:119)
        at java.net.SocketInputStream.read(SocketInputStream.java:176)
        at java.net.SocketInputStream.read(SocketInputStream.java:144)
        at com.tencent.mobileqq.msf.sdk.utils.MonitorSocketInputStream.read(P:57)
        at com.tencent.qphone.base.util.MsfSocketInputBuffer.fillBuffer(P:135)
        at com.tencent.qphone.base.util.MsfSocketInputBuffer.isDataAvailable(P:74)
        at com.tencent.mobileqq.msf.core.net.m$b.run(P:462)
2020-03-12 18:33:26.979 2655-29994/? E/WakeLock: GCM_HB_ALARM release without a matched acquire!
2020-03-12 18:33:26.981 2655-29994/? E/WakeLock: GCM_CONN_ALARM release without a matched acquire!
2020-03-12 18:33:27.066 16568-16568/? E/com.tencent.component.network.module.common.NetworkState: NetworkStateReceiver ====== android.net.conn.CONNECTIVITY_CHANGE
2020-03-12 18:33:27.067 12556-12556/? E/WhiteListUtils: checkIsInWhiteList
2020-03-12 18:33:27.067 12556-12556/? E/WhiteListUtils: time <0 or time < TIME_GAP,so do not send request
2020-03-12 18:33:27.092 1435-1539/? E/GnssLocationProvider: updateNetworkAvailability failed
2020-03-12 18:33:27.097 1435-2091/? E/InputDispatcher: channel '9433e60 io.github.trojan_gfw.igniter/io.github.trojan_gfw.igniter.MainActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
2020-03-12 18:33:27.098 591-591/? E/SELinux: avc:  denied  { find } for service=isub pid=27670 uid=10033 scontext=u:r:mediaprovider:s0:c512,c768 tcontext=u:object_r:radio_service:s0 tclass=service_manager permissive=0
2020-03-12 18:33:27.101 591-591/? E/SELinux: avc:  denied  { find } for service=iphonesubinfo pid=27670 uid=10033 scontext=u:r:mediaprovider:s0:c512,c768 tcontext=u:object_r:radio_service:s0 tclass=service_manager permissive=0
2020-03-12 18:33:27.111 729-799/? E/ANDR-PERF-MPCTL: Invalid profile no. 0, total profiles 0 only
2020-03-12 18:33:27.201 6113-6113/? E/TelephonyEventHandler: Received network connection action
2020-03-12 18:33:27.201 6113-6113/? E/TelephonyEventHandler: Received network connection action currentNwType=1
2020-03-12 18:33:27.444 12556-12556/? E/Launcher: changeViewByFsGestureState,  view=FitSystemWindowView,  alpha=1.0,  scale=1.0
2020-03-12 18:33:27.444 12556-12556/? E/Launcher: changeViewByFsGestureState,  view=ShortcutMenuLayer,  alpha=1.0,  scale=1.0
2020-03-12 18:33:30.116 635-662/? E/Parcel: Reading a NULL string not supported here.
2020-03-12 18:33:30.117 635-662/? E/Parcel: Reading a NULL string not supported here.
2020-03-12 18:33:32.127 24648-25701/? E/PaySafetyCheckManager: start wifi scan task ...
2020-03-12 18:33:40.409 956-1110/? E/storaged: getDiskStats failed with result NOT_SUPPORTED and size 0
2020-03-12 18:33:47.136 2655-30085/? E/WakeLock: GCM_CONN_ALARM release without a matched acquire!
```

**Comment by oasiscifr** [comment]
@GaoZhenGit Does it happen every time you stop the service?

**Comment by GaoZhenGit** [comment]
not every time. It happen sometimes when running the foreground service after several minutes. I can't reproduce it precisely.

**Comment by wongsyrone** [comment]
Please try https://github.com/trojan-gfw/igniter/releases/tag/v0.1.0-pre-alpha17

**Comment by GaoZhenGit** [comment]
Not yet. It seems to be more often.

**Comment by heham** [comment]
没有解决，仍然会出现。

**Comment by wongsyrone** [comment]
https://github.com/trojan-gfw/igniter/issues/129#issuecomment-602691112

**Comment by wongsyrone** [comment]
Please try https://github.com/trojan-gfw/igniter/releases/tag/v0.1.0-pre-alpha18

**Comment by wongsyrone** [comment]
Please try https://github.com/trojan-gfw/igniter/releases/tag/v0.1.0-pre-alpha19

**Comment by heham** [comment]
今天似乎没出现过这个问题，也有可能我今天用的少。
