### ISSUE TITLE
A17 版本不能稳定工作

### ISSUE THREAD

**Issue by jfdnet** [trojan-gfw/igniter#129]
A17版本不能稳定工作
几分钟之内就断流且无法恢复
软件主界面也会失去响应
强制关闭再打开继续工作几分钟之后陷入同样的情况

重新安装A16版本一切正常

Android10

**Comment by KunagisaYuki** [comment]
@jfdnet Would you like to use debug build and provide some logcat info?

**Comment by cuifua** [comment]
me too

**Comment by onlyJinx** [comment]
+1，刚想开issue的，没想到已经有人反馈了

**Comment by wongsyrone** [comment]
请尝试使用绕过APP列表，并且关闭Clash，这样的话会不会有改善。

如果从旧版本升级上来，建议卸载旧版本，关机，开机，安装新版本（也就是需要硬重启一下）

目前发现Clash 可能在特定情况panic

```
03-23 22:03:05.990  6475 10737 I GoLog   : igniter-golib-log: [tun2socks] [proxy] [tcp] [N/A] api.twitter.com:443
03-23 22:03:05.990  6475  6475 E Clash   : clash stopped
03-23 22:03:05.990  6475  6475 I GoLog   : igniter-golib-log: [tun2socks] enter stop
03-23 22:03:05.990  6475  6475 I GoLog   : igniter-golib-log: [tun2socks] begin close tun
03-23 22:03:05.994  6475     0 E Go      : panic: runtime error: invalid memory address or nil pointer dereference
03-23 22:03:05.994  6475     0 E Go      : [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x7d72182e50]
03-23 22:03:05.994  6475     0 E Go      : 
03-23 22:03:05.994  6475     0 E Go      : goroutine 3343 [running]:
03-23 22:03:05.994  6475     0 E Go      : github.com/Dreamacro/clash/component/domain-trie.(*Trie).Search(0x0, 0x4000150280, 0xf, 0x7d71f6b53c)
03-23 22:03:05.994  6475     0 E Go      :      /tmp/gomobile-work-922342425/pkg/mod/github.com/!dreamacro/clash@v0.18.1-0.20200320043530-70a19b999da6/component/domain-trie/tire.go:64 +0x70
03-23 22:03:05.994  6475     0 E Go      : github.com/Dreamacro/clash/component/resolver.ResolveIPv4(0x4000150280, 0xf, 0x7d71fbe5d0, 0x0, 0x4000692540, 0x38, 0x40004d7980)
03-23 22:03:05.994  6475     0 E Go      :      /tmp/gomobile-work-922342425/pkg/mod/github.com/!dreamacro/clash@v0.18.1-0.20200320043530-70a19b999da6/component/resolver/resolver.go:32 +0x38
03-23 22:03:05.994  6475     0 E Go      : github.com/Dreamacro/clash/component/dialer.dualStackDailContext.func1(0x7d72489860, 0x40006927e0, 0x400010c3d0, 0x4, 0x4000150280, 0xf, 0x7d4a332f00)
03-23 22:03:05.995  6475     0 E Go      :      /tmp/gomobile-work-922342425/pkg/mod/github.com/!dreamacro/clash@v0.18.1-0.20200320043530-70a19b999da6/component/dialer/dialer.go:114 +0x2f8
03-23 22:03:05.995  6475     0 E Go      : created by github.com/Dreamacro/clash/component/dialer.dualStackDailContext
03-23 22:03:05.995  6475     0 E Go      :      /tmp/gomobile-work-922342425/pkg/mod/github.com/!dreamacro/clash@v0.18.1-0.20200320043530-70a19b999da6/component/dialer/dialer.go:127 +0x1a8
03-23 22:03:05.995  6475 10737 E GoLog   : panic: runtime error: invalid memory address or nil pointer dereference
--------- beginning of crash
03-23 22:03:05.995  6475  3786 F libc    : Fatal signal 6 (SIGABRT), code -6 (SI_TKILL) in tid 3786 (jan_gfw.igniter), pid 6475 (jan_gfw.igniter)
03-23 22:03:06.103  1218  2012 D VPN     : NetworkAgent: NetworkAgent channel lost
03-23 22:03:06.109 18032 18508 E libc    : Access denied finding property "net.dns1"
03-23 22:03:06.115 17894 18323 E libc    : Access denied finding property "net.dns1"
03-23 22:03:06.118 18032 18508 E libc    : Access denied finding property "net.dns1"
03-23 22:03:06.120 17894 18323 E libc    : Access denied finding property "net.dns1"
03-23 22:03:06.137 18032 18508 E libc    : Access denied finding property "net.dns1"
03-23 22:03:06.139 17894 18323 E libc    : Access denied finding property "net.dns1"
03-23 22:03:06.170 21222 21222 F DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
03-23 22:03:06.170 21222 21222 F DEBUG   : Build fingerprint: 'samsung/beyond2qltezh/beyond2q:10/QP1A.190711.020/G9750ZHU3BTC3:user/release-keys'
03-23 22:03:06.170 21222 21222 F DEBUG   : Revision: '17'
03-23 22:03:06.170 21222 21222 F DEBUG   : ABI: 'arm64'
03-23 22:03:06.170 21222 21222 F DEBUG   : Timestamp: 2020-03-23 22:03:06+0800
03-23 22:03:06.170 21222 21222 F DEBUG   : pid: 6475, tid: 3786, name: jan_gfw.igniter  >>> io.github.trojan_gfw.igniter <<<
03-23 22:03:06.170 21222 21222 F DEBUG   : uid: 10438
03-23 22:03:06.170 21222 21222 F DEBUG   : signal 6 (SIGABRT), code -6 (SI_TKILL), fault addr --------
03-23 22:03:06.170 21222 21222 F DEBUG   :     x0  0000000000000000  x1  0000000000000eca  x2  0000000000000006  x3  0000000000000008
03-23 22:03:06.170 21222 21222 F DEBUG   :     x4  0000000000000001  x5  0000007d722e16c8  x6  000000000000003f  x7  0000000000000030
03-23 22:03:06.170 21222 21222 F DEBUG   :     x8  0000000000000083  x9  000000000000008e  x10 000000000000000a  x11 0000007d727394d6
03-23 22:03:06.170 21222 21222 F DEBUG   :     x12 0000000000000000  x13 0000000000000000  x14 0000000000000000  x15 0000000000000001
03-23 22:03:06.170 21222 21222 F DEBUG   :     x16 0000007d71fc1ae3  x17 0000007d71fc1ae0  x18 0000007d364b4000  x19 000000000000194b
03-23 22:03:06.170 21222 21222 F DEBUG   :     x20 0000007dd379b770  x21 000000400018ca80  x22 000000000000005a  x23 0000007dd379bdd8
03-23 22:03:06.170 21222 21222 F DEBUG   :     x24 0000007dd379bd50  x25 0000007dd379bd50  x26 0000000000000000  x27 0000000000000010
03-23 22:03:06.170 21222 21222 F DEBUG   :     x28 00000040004d7980  x29 0000000000000000
03-23 22:03:06.170 21222 21222 F DEBUG   :     sp  000000400049bc00  lr  0000007d71fa9f50  pc  0000007d71fc2848
03-23 22:03:06.173 21222 21222 F DEBUG   : 
03-23 22:03:06.173 21222 21222 F DEBUG   : backtrace:
03-23 22:03:06.173 21222 21222 F DEBUG   :       #00 pc 0000000000281848  /data/app/io.github.trojan_gfw.igniter-iOmc6sOBeLnBgHESj-LCtA==/lib/arm64/libgojni.so
```

**Comment by wongsyrone** [comment]
Please test this version, it's signed by my keystore, please uninstall the old one before testing.

https://drive.google.com/file/d/1V5VUAJLH_iAdS8qYJBOVp5ib7n8VYcfO/view?usp=sharing

**Comment by cuifua** [comment]
想知道exempt apps 打开开关是指的这个ppt走这个代理还是不走这个代理

**Comment by wongsyrone** [comment]
> 想知道exempt apps 打开开关是指的这个app走这个代理还是不走这个代理

不走这个代理

**Comment by wongsyrone** [comment]
Please try https://github.com/trojan-gfw/igniter/releases/tag/v0.1.0-pre-alpha18

**Comment by onlyJinx** [comment]
A18用着用着会突然崩溃
![Screenshot_20200324-102836_eleme](https://user-images.githubusercontent.com/21324835/77382112-70152500-6dba-11ea-8eae-fec2c989ed5d.jpg)

**Comment by Ltre** [comment]
galaxy oneui 2.0
crashed after few minutes

**Comment by zhangzhhz** [comment]
上面提到的A17、A18的问题，也都碰到了。

**Comment by wongsyrone** [comment]
Please try https://github.com/trojan-gfw/igniter/releases/tag/v0.1.0-pre-alpha19

**Comment by jfdnet** [comment]
> Please try https://github.com/trojan-gfw/igniter/releases/tag/v0.1.0-pre-alpha19

19版本使用了一个多小时 一切如常
