### ISSUE TITLE
App crash when click "Server List"

### ISSUE THREAD

**Issue by wangxl056** [trojan-gfw/igniter#160]
Device: Honor 7
Logcat:
Process: io.github.trojan_gfw.igniter, PID: 9460
    android.content.res.Resources$NotFoundException: Resource ID #0x7f080078
        at android.content.res.Resources.getValue(Resources.java:1384)
        at android.support.v7.widget.AppCompatDrawableManager.loadDrawableFromDelegates(AppCompatDrawableManager.java:331)
        at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:198)
        at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:191)
        at android.support.v7.content.res.AppCompatResources.getDrawable(AppCompatResources.java:102)
        at android.support.v7.view.menu.MenuItemImpl.getIcon(MenuItemImpl.java:505)
        at android.support.v7.view.menu.ActionMenuItemView.initialize(ActionMenuItemView.java:126)
        at android.support.v7.widget.ActionMenuPresenter.bindItemView(ActionMenuPresenter.java:211)
        at android.support.v7.view.menu.BaseMenuPresenter.getItemView(BaseMenuPresenter.java:188)
        at android.support.v7.widget.ActionMenuPresenter.getItemView(ActionMenuPresenter.java:197)
        at android.support.v7.widget.ActionMenuPresenter.flagActionItems(ActionMenuPresenter.java:506)
        at android.support.v7.view.menu.MenuBuilder.flagActionItems(MenuBuilder.java:1182)
        at android.support.v7.view.menu.BaseMenuPresenter.updateMenuView(BaseMenuPresenter.java:96)
        at android.support.v7.widget.ActionMenuPresenter.updateMenuView(ActionMenuPresenter.java:230)
        at android.support.v7.view.menu.MenuBuilder.dispatchPresenterUpdate(MenuBuilder.java:298)
        at android.support.v7.view.menu.MenuBuilder.onItemsChanged(MenuBuilder.java:1069)
        at android.support.v7.view.menu.MenuBuilder.startDispatchingItemsChanged(MenuBuilder.java:1096)
        at android.support.v7.app.AppCompatDelegateImpl.preparePanel(AppCompatDelegateImpl.java:1631)
        at android.support.v7.app.AppCompatDelegateImpl.doInvalidatePanelMenu(AppCompatDelegateImpl.java:1869)
        at android.support.v7.app.AppCompatDelegateImpl$2.run(AppCompatDelegateImpl.java:230)
        at android.os.Handler.handleCallback(Handler.java:743)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:150)

**Comment by TchaikovDriver** [comment]
What's the Android version of your phone?

**Comment by TchaikovDriver** [comment]
The bug is fixed in the next release.

**Comment by wangxl056** [comment]
> What's the Android version of your phone?

Model：PL-TL01H
System Version：EMUI 4.0.3
Android Version：6.0
Resolution：1080 x 1920

**Comment by wongsyrone** [comment]
Please follow instructions on the release page: https://github.com/trojan-gfw/igniter/releases/tag/v0.1.0-pre-alpha21
