### ISSUE TITLE
Crash: ping: Comparison method violates its general contract!

### ISSUE THREAD

**Issue by wongsyrone** [trojan-gfw/igniter#303]
```
2020-09-27 13:17:47.838 10897-10897/io.github.trojan_gfw.igniter.debug E/AndroidRuntime: FATAL EXCEPTION: main
    Process: io.github.trojan_gfw.igniter.debug, PID: 10897
    java.lang.IllegalArgumentException: Comparison method violates its general contract!
        at java.util.TimSort.mergeLo(TimSort.java:777)
        at java.util.TimSort.mergeAt(TimSort.java:514)
        at java.util.TimSort.mergeForceCollapse(TimSort.java:457)
        at java.util.TimSort.sort(TimSort.java:254)
        at java.util.Arrays.sort(Arrays.java:1492)
        at java.util.ArrayList.sort(ArrayList.java:1470)
        at java.util.Collections.sort(Collections.java:206)
        at io.github.trojan_gfw.igniter.servers.fragment.ServerListAdapter.sortConfigByDelayTime(ServerListAdapter.java:143)
        at io.github.trojan_gfw.igniter.servers.fragment.ServerListAdapter.setPingServerDelayTime(ServerListAdapter.java:94)
        at io.github.trojan_gfw.igniter.servers.fragment.ServerListFragment.setPingServerDelayTime(ServerListFragment.java:440)
        at io.github.trojan_gfw.igniter.servers.presenter.ServerListPresenter.lambda$setPingDelayTime$2$ServerListPresenter(ServerListPresenter.java:247)
        at io.github.trojan_gfw.igniter.servers.presenter.-$$Lambda$ServerListPresenter$m9_ym-tJpLACp8cwF0DZ2s69g3I.run(Unknown Source:6)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
```

**Comment by wongsyrone** [comment]
Fixed via https://github.com/trojan-gfw/igniter/commit/313360088cc4e23353bd2617b99cd7aef5eafc3e
