### ISSUE TITLE
Test error on Android 6.0

### ISSUE THREAD

**Issue by design-study** [trojan-gfw/igniter#358]
When I run on the Android 6 emulator, I can connect to the server, but the test will fail.

```
04-13 09:43:57.639 4367-4367/io.github.trojan_gfw.igniter.debug E/MainActivity: TestError: recvfrom failed: ECONNRESET (Connection reset by peer)
```

Environment:

* Android SDK version: 23
* Emulator CPU/ABI: x86_64
* igniter version: c2261a97 (https://github.com/trojan-gfw/igniter/commit/c2261a97406f0fa84987e3cbfbed6dfcfaff3ca5)
* igniter-go-libs version: 72ba215 (https://github.com/trojan-gfw/igniter-go-libs/commit/72ba215843cf9c25ef13a14b641dd7410fe1bf36)
* libs version: 8fde414 (https://github.com/trojan-gfw/igniter-libs/tree/8fde414e3ebf0f28ab40f5835ad0d47ee85758c5)
* trojan version: 8606b71 (https://github.com/trojan-gfw/trojan/tree/8606b7110fe79f8ab02d60c897f87ffb0a9b23f0)

**Comment by wongsyrone** [comment]
Please obtain the log via instructions in https://github.com/trojan-gfw/igniter/issues/197

**Comment by design-study** [comment]
```
04-13 10:44:09.421 6317-6397/io.github.trojan_gfw.igniter.debug E/TestConnection: testLatency: 
    java.net.SocketException: recvfrom failed: ECONNRESET (Connection reset by peer)
        at libcore.io.IoBridge.maybeThrowAfterRecvfrom(IoBridge.java:588)
        at libcore.io.IoBridge.recvfrom(IoBridge.java:552)
        at java.net.PlainSocketImpl.read(PlainSocketImpl.java:481)
        at java.net.PlainSocketImpl.-wrap0(PlainSocketImpl.java)
        at java.net.PlainSocketImpl$PlainSocketInputStream.read(PlainSocketImpl.java:237)
        at java.net.PlainSocketImpl.socksReadReply(PlainSocketImpl.java:436)
        at java.net.PlainSocketImpl.socksRequestConnection(PlainSocketImpl.java:336)
        at java.net.PlainSocketImpl.socksConnect(PlainSocketImpl.java:322)
        at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:181)
        at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:452)
        at java.net.Socket.connect(Socket.java:884)
        at com.android.okhttp.internal.Platform.connectSocket(Platform.java:117)
        at com.android.okhttp.internal.http.SocketConnector.connectRawSocket(SocketConnector.java:160)
        at com.android.okhttp.internal.http.SocketConnector.connectTls(SocketConnector.java:79)
        at com.android.okhttp.Connection.connect(Connection.java:143)
        at com.android.okhttp.Connection.connectAndSetOwner(Connection.java:185)
        at com.android.okhttp.OkHttpClient$1.connectAndSetOwner(OkHttpClient.java:128)
        at com.android.okhttp.internal.http.HttpEngine.nextConnection(HttpEngine.java:341)
        at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:330)
        at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:248)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:433)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:114)
        at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.connect(DelegatingHttpsURLConnection.java:89)
        at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java)
        at io.github.trojan_gfw.igniter.connection.TestConnection.testLatency(TestConnection.java:31)
        at io.github.trojan_gfw.igniter.ProxyService$2.lambda$testConnection$0$ProxyService$2(ProxyService.java:132)
        at io.github.trojan_gfw.igniter.-$$Lambda$ProxyService$2$QacmkbQALJnA2U-5HknAVYvMPp4.run(lambda)
        at java.lang.Thread.run(Thread.java:818)
     Caused by: android.system.ErrnoException: recvfrom failed: ECONNRESET (Connection reset by peer)
        at libcore.io.Posix.recvfromBytes(Native Method)
        at libcore.io.Posix.recvfrom(Posix.java:189)
        at libcore.io.BlockGuardOs.recvfrom(BlockGuardOs.java:250)
        at libcore.io.IoBridge.recvfrom(IoBridge.java:549)
        at java.net.PlainSocketImpl.read(PlainSocketImpl.java:481) 
        at java.net.PlainSocketImpl.-wrap0(PlainSocketImpl.java) 
        at java.net.PlainSocketImpl$PlainSocketInputStream.read(PlainSocketImpl.java:237) 
        at java.net.PlainSocketImpl.socksReadReply(PlainSocketImpl.java:436) 
        at java.net.PlainSocketImpl.socksRequestConnection(PlainSocketImpl.java:336) 
        at java.net.PlainSocketImpl.socksConnect(PlainSocketImpl.java:322) 
        at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:181) 
        at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:452) 
        at java.net.Socket.connect(Socket.java:884) 
        at com.android.okhttp.internal.Platform.connectSocket(Platform.java:117) 
        at com.android.okhttp.internal.http.SocketConnector.connectRawSocket(SocketConnector.java:160) 
        at com.android.okhttp.internal.http.SocketConnector.connectTls(SocketConnector.java:79) 
        at com.android.okhttp.Connection.connect(Connection.java:143) 
        at com.android.okhttp.Connection.connectAndSetOwner(Connection.java:185) 
        at com.android.okhttp.OkHttpClient$1.connectAndSetOwner(OkHttpClient.java:128) 
        at com.android.okhttp.internal.http.HttpEngine.nextConnection(HttpEngine.java:341) 
        at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:330) 
        at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:248) 
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:433) 
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:114) 
        at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.connect(DelegatingHttpsURLConnection.java:89) 
        at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java) 
        at io.github.trojan_gfw.igniter.connection.TestConnection.testLatency(TestConnection.java:31) 
        at io.github.trojan_gfw.igniter.ProxyService$2.lambda$testConnection$0$ProxyService$2(ProxyService.java:132) 
        at io.github.trojan_gfw.igniter.-$$Lambda$ProxyService$2$QacmkbQALJnA2U-5HknAVYvMPp4.run(lambda) 
        at java.lang.Thread.run(Thread.java:818) 

```

**Comment by wongsyrone** [comment]
@design-study Please post your kernel version

**Comment by design-study** [comment]
@wongsyrone 

![Screenshot_1619172230](https://user-images.githubusercontent.com/7581969/115861100-f6d87d80-a464-11eb-839a-68f047032e3b.png)

**Comment by wongsyrone** [comment]
> Depending on the environment, the emulator may not be able to support other protocols (such as ICMP, used for "ping") might not be supported. 

https://www.androidcookbook.info/android-system/emulator-networking.html

I cannot reproduce the issue.

**Comment by design-study** [comment]
The Android 6.0 (API 23) emulator should be fine. After the service is connected, you can access the Google search homepage opening the browser. Using the adb shell to detect, the simulator can execute the ping command.

The problem is that clicking the test button in the app reports an error.

**Comment by hoorace** [comment]
I encountered the same problem, this is my device information.
![Uploading Screenshot.png…]()
