### ISSUE TITLE
连接问题

### ISSUE THREAD

**Issue by php168Sura** [trojan-gfw/igniter#364]
在OnePlus 8 Pro设备中运行，单击“链接”->再点击“断开连接”->再点击“连接”后会出现界面错乱问题。本应点击“连接”会出现“断开连接” ”，但是在OnePlus 8 Pro设备中它不会有变化。

**Comment by TchaikovDriver** [comment]
麻烦贴一下logcat日志

**Comment by wongsyrone** [comment]
使用的是哪个版本

**Comment by php168Sura** [comment]
> 使用的是哪个版本

io.github.trojan_gfw.igniter-v0.10.3-beta-230001003-universal-release.apk
使用的这个

**Comment by php168Sura** [comment]
> 麻烦贴一下logcat日志

我直接使用的apk安装包，在哪有日志文件吗？

**Comment by wongsyrone** [comment]
https://github.com/trojan-gfw/igniter/issues/197

**Comment by php168Sura** [comment]
> [＃197](https://github.com/trojan-gfw/igniter/issues/197)

2021-04-25 10:24:20.151 9807-9807/io.github.trojan_gfw.igniter.debug V/TrojanConfig: {"local_addr":"127.0.0.1","local_port":1081,"remote_server_remark":"比例","remote_addr":"9527.click","remote_port":18888,"password":[""],"log_level":2,"ssl":{"verify":true,"cert":"\/data\/user\/0\/io.github.trojan_gfw.igniter.debug\/cache\/cacert.pem","cipher":"","cipher_tls13":"","alpn":["h2","http\/1.1"],"sni":"9527.click"},"enable_ipv6":false}
2021-04-25 10:24:20.162 9807-3721/io.github.trojan_gfw.igniter.debug I/PreferencesProvider: query values with: io.github.trojan_gfw.igniter.common.os.PreferencesProvider@1dd4f1d
2021-04-25 10:24:20.171 9807-9807/io.github.trojan_gfw.igniter.debug I/MainActivity: onStateChanged# state: 0 msg: {"port":-1}
2021-04-25 10:24:20.199 9807-3721/io.github.trojan_gfw.igniter.debug I/PreferencesProvider: query values with: io.github.trojan_gfw.igniter.common.os.PreferencesProvider@1dd4f1d
2021-04-25 10:24:20.203 9807-3721/io.github.trojan_gfw.igniter.debug I/PreferencesProvider: query values with: io.github.trojan_gfw.igniter.common.os.PreferencesProvider@1dd4f1d
2021-04-25 10:24:20.207 9807-3721/io.github.trojan_gfw.igniter.debug I/PreferencesProvider: query values with: io.github.trojan_gfw.igniter.common.os.PreferencesProvider@1dd4f1d
2021-04-25 10:24:20.318 9807-9807/io.github.trojan_gfw.igniter.debug I/MainActivity: onStateChanged# state: 1 msg: {"port":37851}
2021-04-25 10:24:25.206 9807-9807/io.github.trojan_gfw.igniter.debug I/MainActivity: onStateChanged# state: 2 msg: {"msg":"state changed"}
2021-04-25 10:24:25.313 9807-9807/io.github.trojan_gfw.igniter.debug I/MainActivity: onStateChanged# state: 3 msg: {"msg":"state changed"}
2021-04-25 10:24:25.361 9807-3721/io.github.trojan_gfw.igniter.debug I/TetheringManager: registerTetheringEventCallback:io.github.trojan_gfw.igniter.debug
2021-04-25 10:24:25.460 9807-9807/io.github.trojan_gfw.igniter.debug W/System.err: android.os.DeadObjectException
2021-04-25 10:24:25.461 9807-9807/io.github.trojan_gfw.igniter.debug W/System.err:     at android.os.BinderProxy.transactNative(Native Method)
2021-04-25 10:24:25.461 9807-9807/io.github.trojan_gfw.igniter.debug W/System.err:     at android.os.BinderProxy.transact(BinderProxy.java:591)
2021-04-25 10:24:25.461 9807-9807/io.github.trojan_gfw.igniter.debug W/System.err:     at io.github.trojan_gfw.igniter.proxy.aidl.ITrojanService$Stub$Proxy.unregisterCallback(ITrojanService.java:275)
2021-04-25 10:24:25.461 9807-9807/io.github.trojan_gfw.igniter.debug W/System.err:     at io.github.trojan_gfw.igniter.connection.TrojanConnection.unregisterServiceCallback(TrojanConnection.java:135)
2021-04-25 10:24:25.461 9807-9807/io.github.trojan_gfw.igniter.debug W/System.err:     at io.github.trojan_gfw.igniter.connection.TrojanConnection.onServiceDisconnected(TrojanConnection.java:175)
2021-04-25 10:24:25.461 9807-9807/io.github.trojan_gfw.igniter.debug W/System.err:     at android.app.LoadedApk$ServiceDispatcher.doDeath(LoadedApk.java:1998)
2021-04-25 10:24:25.461 9807-9807/io.github.trojan_gfw.igniter.debug W/System.err:     at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:2013)
2021-04-25 10:24:25.461 9807-9807/io.github.trojan_gfw.igniter.debug W/System.err:     at android.os.Handler.handleCallback(Handler.java:938)
2021-04-25 10:24:25.461 9807-9807/io.github.trojan_gfw.igniter.debug W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:99)
2021-04-25 10:24:25.461 9807-9807/io.github.trojan_gfw.igniter.debug W/System.err:     at android.os.Looper.loop(Looper.java:233)
2021-04-25 10:24:25.461 9807-9807/io.github.trojan_gfw.igniter.debug W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:8010)
2021-04-25 10:24:25.461 9807-9807/io.github.trojan_gfw.igniter.debug W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
2021-04-25 10:24:25.462 9807-9807/io.github.trojan_gfw.igniter.debug W/System.err:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:631)
2021-04-25 10:24:25.462 9807-9807/io.github.trojan_gfw.igniter.debug W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:978)
2021-04-25 10:24:25.462 9807-9807/io.github.trojan_gfw.igniter.debug I/MainActivity: onServiceDisconnected
2021-04-25 10:24:29.427 9807-9807/io.github.trojan_gfw.igniter.debug V/TrojanConfig: {"local_addr":"127.0.0.1","local_port":1081,"remote_server_remark":"比例","remote_addr":"9527.click","remote_port":18888,"password":[""],"log_level":2,"ssl":{"verify":true,"cert":"\/data\/user\/0\/io.github.trojan_gfw.igniter.debug\/cache\/cacert.pem","cipher":"":"","alpn":["h2","http\/1.1"],"sni":"9527.click"},"enable_ipv6":false}
2021-04-25 10:24:29.662 9807-4448/io.github.trojan_gfw.igniter.debug I/PreferencesProvider: query values with: io.github.trojan_gfw.igniter.common.os.PreferencesProvider@1dd4f1d
2021-04-25 10:24:29.690 9807-4448/io.github.trojan_gfw.igniter.debug I/PreferencesProvider: query values with: io.github.trojan_gfw.igniter.common.os.PreferencesProvider@1dd4f1d
2021-04-25 10:24:29.695 9807-4448/io.github.trojan_gfw.igniter.debug I/PreferencesProvider: query values with: io.github.trojan_gfw.igniter.common.os.PreferencesProvider@1dd4f1d
2021-04-25 10:24:29.698 9807-4448/io.github.trojan_gfw.igniter.debug I/PreferencesProvider: query values with: io.github.trojan_gfw.igniter.common.os.PreferencesProvider@1dd4f1d
2021-04-25 10:24:48.929 9807-9807/io.github.trojan_gfw.igniter.debug V/TrojanConfig: {"local_addr":"127.0.0.1","local_port":1081,"remote_server_remark":"比例","remote_addr":"9527.click","remote_port":18888,"password":[""],"log_level":2,"ssl":{"verify":true,"cert":"\/data\/user\/0\/io.github.trojan_gfw.igniter.debug\/cache\/cacert.pem","cipher":"","cipher_tls13":"","alpn":["h2","http\/1.1"],"sni":"9527.click"},"enable_ipv6":false}
2021-04-25 10:24:48.938 9807-4448/io.github.trojan_gfw.igniter.debug I/PreferencesProvider: query values with: io.github.trojan_gfw.igniter.common.os.PreferencesProvider@1dd4f1d
2021-04-25 10:24:48.960 9807-4448/io.github.trojan_gfw.igniter.debug I/PreferencesProvider: query values with: io.github.trojan_gfw.igniter.common.os.PreferencesProvider@1dd4f1d
2021-04-25 10:24:48.963 9807-4448/io.github.trojan_gfw.igniter.debug I/PreferencesProvider: query values with: io.github.trojan_gfw.igniter.common.os.PreferencesProvider@1dd4f1d
2021-04-25 10:24:48.965 9807-4448/io.github.trojan_gfw.igniter.debug I/PreferencesProvider: query values with: io.github.trojan_gfw.igniter.common.os.PreferencesProvider@1dd4f1d

**Comment by php168Sura** [comment]
它没有报错。但是第二次连接时那个状态改变的监听没收到

**Comment by TchaikovDriver** [comment]
你试一下进入应用设置，把电源优化设置为不优化，不禁用igniter的后台

**Comment by php168Sura** [comment]
> 你试一下进入应用设置，把电源优化设置为不优化，不禁用igniter的后台
这样可以解决问题，非常感谢
