### ISSUE TITLE
An error will be reported when vpn is closed, and the system vpn connection cannot be closed in android 11

### ISSUE THREAD

**Issue by weew2** [trojan-gfw/igniter#366]
Android SDK version: 30
System: win 10
igniter version: 0.10.3

error log:

2021-04-29 14:06:17.659 24713-24713/io.github.trojan_gfw.igniter.debug W/System.err: android.os.DeadObjectException
2021-04-29 14:06:17.659 24713-24713/io.github.trojan_gfw.igniter.debug W/System.err:     at android.os.BinderProxy.transactNative(Native Method)
2021-04-29 14:06:17.659 24713-24713/io.github.trojan_gfw.igniter.debug W/System.err:     at android.os.BinderProxy.transact(Binder.java:1133)
2021-04-29 14:06:17.659 24713-24713/io.github.trojan_gfw.igniter.debug W/System.err:     at io.github.trojan_gfw.igniter.proxy.aidl.ITrojanService$Stub$Proxy.unregisterCallback(ITrojanService.java:275)
2021-04-29 14:06:17.659 24713-24713/io.github.trojan_gfw.igniter.debug W/System.err:     at io.github.trojan_gfw.igniter.connection.TrojanConnection.unregisterServiceCallback(TrojanConnection.java:132)
2021-04-29 14:06:17.659 24713-24713/io.github.trojan_gfw.igniter.debug W/System.err:     at io.github.trojan_gfw.igniter.connection.TrojanConnection.onServiceDisconnected(TrojanConnection.java:172)
2021-04-29 14:06:17.659 24713-24713/io.github.trojan_gfw.igniter.debug W/System.err:     at android.app.LoadedApk$ServiceDispatcher.doDeath(LoadedApk.java:1757)
2021-04-29 14:06:17.659 24713-24713/io.github.trojan_gfw.igniter.debug W/System.err:     at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:1772)
2021-04-29 14:06:17.659 24713-24713/io.github.trojan_gfw.igniter.debug W/System.err:     at android.os.Handler.handleCallback(Handler.java:873)
2021-04-29 14:06:17.659 24713-24713/io.github.trojan_gfw.igniter.debug W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:99)
2021-04-29 14:06:17.659 24713-24713/io.github.trojan_gfw.igniter.debug W/System.err:     at android.os.Looper.loop(Looper.java:201)
2021-04-29 14:06:17.660 24713-24713/io.github.trojan_gfw.igniter.debug W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:6810)
2021-04-29 14:06:17.660 24713-24713/io.github.trojan_gfw.igniter.debug W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
2021-04-29 14:06:17.660 24713-24713/io.github.trojan_gfw.igniter.debug W/System.err:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
2021-04-29 14:06:17.660 24713-24713/io.github.trojan_gfw.igniter.debug W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)

**Comment by weew2** [comment]
igniter-go 0.10.3
igniter-go-libs 1.27
igniter-libs   https://github.com/trojan-gfw/igniter-libs/tree/ebfd02c656ccccff25ad5b122e7758cdb78fedcf
trojan 1.16.0

**Comment by wongsyrone** [comment]
igniter-go?

**Comment by weew2** [comment]
发错了，多了个go

**Comment by LaoHuan** [comment]
> 点火器去吗？

老大。改哪能让speedtest测起来喃？是哪里做了限制吗？

**Comment by weew2** [comment]
It has been processed, just set the death monitor to true

TrojanConnection connection = new TrojanConnection(true)

**Comment by wongsyrone** [comment]
@TchaikovDriver Any idea on changing the value of `linkToDeath` to true?

**Comment by TchaikovDriver** [comment]
That's just for observing the death of `ProxyService`. Since we have handled the `STOPPING` and `STOPPED` event, listening for the death event seems to be useless.

**Comment by weew2** [comment]
It is valuable. The proxy service on OnePlus is always closed. This is the time to trigger the death monitor to restart.
