### ISSUE TITLE
bug report

### ISSUE THREAD

**Issue by xueshiji** [trojan-gfw/igniter#400]
java.lang.RuntimeException: Unable to start service io.github.trojan_gfw.igniter.ProxyService@17d67d7 with Intent { cmp=io.github.trojan_gfw.igniter/.ProxyService }: java.lang.IllegalArgumentException: io.github.trojan_gfw.igniter: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4800)
	at android.app.ActivityThread.access$2100(ActivityThread.java:274)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2166)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:210)
	at android.os.Looper.loop(Looper.java:299)
	at android.app.ActivityThread.main(ActivityThread.java:8261)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1045)
Caused by: java.lang.IllegalArgumentException: io.github.trojan_gfw.igniter: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
	at android.app.PendingIntent.checkFlags(PendingIntent.java:375)
	at android.app.PendingIntent.getActivityAsUser(PendingIntent.java:458)
	at android.app.PendingIntent.getActivity(PendingIntent.java:444)
	at android.app.PendingIntent.getActivity(PendingIntent.java:408)
	at io.github.trojan_gfw.igniter.ProxyService.onStartCommand(:3)
	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4782)
	... 9 more

**Comment by wongsyrone** [comment]
https://github.com/trojan-gfw/igniter/issues/399
