### ISSUE TITLE
huawei m6 高能版安装后没有效果

### ISSUE THREAD

**Issue by obnews** [trojan-gfw/igniter#73]
vps搭建好后在windows上测试正常。
huawei m6 高能版安装后没有效果
安的是igniter-0.1.0-pre-alpha13版本

**Comment by GreaterFire** [comment]
Please provide logcat.

**Comment by defghy** [comment]
2020-06-08 09:51:59.401 13265-13265/? E/w.igniter:prox: [qarth_debug:]  get PatchStore::createDisableExceptionQarthFile method fail.
    
    --------- beginning of crash
2020-06-08 09:51:59.402 13265-13265/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: io.github.trojan_gfw.igniter:proxy, PID: 13265
    java.lang.RuntimeException: Unable to start service io.github.trojan_gfw.igniter.ProxyService@770844a with Intent { cmp=io.github.trojan_gfw.igniter/.ProxyService (has extras) }: java.lang.SecurityException: getPackageUid: Neither user 10121 nor current process has android.permission.INTERACT_ACROSS_USERS.
        at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4337)
        at android.app.ActivityThread.access$2700(ActivityThread.java:259)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2079)
        at android.os.Handler.dispatchMessage(Handler.java:112)
        at android.os.Looper.loop(Looper.java:216)
        at android.app.ActivityThread.main(ActivityThread.java:7586)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1034)
     Caused by: java.lang.SecurityException: getPackageUid: Neither user 10121 nor current process has android.permission.INTERACT_ACROSS_USERS.
        at android.os.Parcel.createException(Parcel.java:1953)
        at android.os.Parcel.readException(Parcel.java:1921)
        at android.os.Parcel.readException(Parcel.java:1871)
        at android.net.IConnectivityManager$Stub$Proxy.establishVpn(IConnectivityManager.java:1996)
        at android.net.VpnService$Builder.establish(VpnService.java:820)
        at io.github.trojan_gfw.igniter.ProxyService.onStartCommand(ProxyService.java:322)
        at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4316)
        at android.app.ActivityThread.access$2700(ActivityThread.java:259) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2079) 
        at android.os.Handler.dispatchMessage(Handler.java:112) 
        at android.os.Looper.loop(Looper.java:216) 
        at android.app.ActivityThread.main(ActivityThread.java:7586) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1034) 
     Caused by: android.os.RemoteException: Remote stack trace:
        at android.app.ContextImpl.enforce(Ljava/lang/String;IZILjava/lang/String;)V(libmapleframework.so:3872781)
        at android.app.ContextImpl.enforceCallingOrSelfPermission(Ljava/lang/String;Ljava/lang/String;)V(libmapleframework.so:4351001)
        at com.android.server.pm.permission.PermissionManagerService.enforceCrossUserPermission(IIZZZLjava/lang/String;)V(libmapleservices.so:2971893)
        at com.android.server.pm.PackageManagerService.getPackageUid(Ljava/lang/String;II)I(libmapleservices.so:3050209)
        at huawei.android.app.HwApiCacheMangerEx.getPackageUidAsUser(Landroid/content/pm/IPackageManager;Ljava/lang/String;II)I(libmaplehwEmui.so:665593)
2020-06-08 09:52:00.450 13331-13331/? E/w.igniter:prox: Not starting debugger since process cannot load the jdwp agent.
2020-06-08 09:52:00.530 1197-1197/? E/NotificationService: Muting recently noisy 0|io.github.trojan_gfw.igniter|114514|null|10121
2020-06-08 09:52:00.593 13331-13331/? E/w.igniter:prox: [qarth_debug:]  get PatchStore::createDisableExceptionQarthFile method fail.
2020-06-08 09:52:00.594 13331-13331/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: io.github.trojan_gfw.igniter:proxy, PID: 13331
    java.lang.RuntimeException: Unable to start service io.github.trojan_gfw.igniter.ProxyService@770844a with Intent { cmp=io.github.trojan_gfw.igniter/.ProxyService (has extras) }: java.lang.SecurityException: getPackageUid: Neither user 10121 nor current process has android.permission.INTERACT_ACROSS_USERS.
        at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4337)
        at android.app.ActivityThread.access$2700(ActivityThread.java:259)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2079)
        at android.os.Handler.dispatchMessage(Handler.java:112)
        at android.os.Looper.loop(Looper.java:216)
        at android.app.ActivityThread.main(ActivityThread.java:7586)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1034)
     Caused by: java.lang.SecurityException: getPackageUid: Neither user 10121 nor current process has android.permission.INTERACT_ACROSS_USERS.
        at android.os.Parcel.createException(Parcel.java:1953)
        at android.os.Parcel.readException(Parcel.java:1921)
        at android.os.Parcel.readException(Parcel.java:1871)
        at android.net.IConnectivityManager$Stub$Proxy.establishVpn(IConnectivityManager.java:1996)
        at android.net.VpnService$Builder.establish(VpnService.java:820)
        at io.github.trojan_gfw.igniter.ProxyService.onStartCommand(ProxyService.java:322)
        at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4316)
        at android.app.ActivityThread.access$2700(ActivityThread.java:259) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2079) 
        at android.os.Handler.dispatchMessage(Handler.java:112) 
        at android.os.Looper.loop(Looper.java:216) 
        at android.app.ActivityThread.main(ActivityThread.java:7586) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1034) 
     Caused by: android.os.RemoteException: Remote stack trace:
        at android.app.ContextImpl.enforce(Ljava/lang/String;IZILjava/lang/String;)V(libmapleframework.so:3872781)
        at android.app.ContextImpl.enforceCallingOrSelfPermission(Ljava/lang/String;Ljava/lang/String;)V(libmapleframework.so:4351001)
        at com.android.server.pm.permission.PermissionManagerService.enforceCrossUserPermission(IIZZZLjava/lang/String;)V(libmapleservices.so:2971893)
        at com.android.server.pm.PackageManagerService.getPackageUid(Ljava/lang/String;II)I(libmapleservices.so:3050209)
        at huawei.android.app.HwApiCacheMangerEx.getPackageUidAsUser(Landroid/content/pm/IPackageManager;Ljava/lang/String;II)I(libmaplehwEmui.so:665593)
2020-06-08 09:52:01.642 13370-13370/? E/w.igniter:prox: Not starting debugger since process cannot load the jdwp agent.
2020-06-08 09:52:01.735 1197-1197/? E/NotificationService: Muting recently noisy 0|io.github.trojan_gfw.igniter|114514|null|10121
2020-06-08 09:52:01.812 13370-13370/? E/w.igniter:prox: [qarth_debug:]  get PatchStore::createDisableExceptionQarthFile method fail.
2020-06-08 09:52:01.813 13370-13370/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: io.github.trojan_gfw.igniter:proxy, PID: 13370
    java.lang.RuntimeException: Unable to start service io.github.trojan_gfw.igniter.ProxyService@770844a with Intent { cmp=io.github.trojan_gfw.igniter/.ProxyService (has extras) }: java.lang.SecurityException: getPackageUid: Neither user 10121 nor current process has android.permission.INTERACT_ACROSS_USERS.
        at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4337)
        at android.app.ActivityThread.access$2700(ActivityThread.java:259)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2079)
        at android.os.Handler.dispatchMessage(Handler.java:112)
        at android.os.Looper.loop(Looper.java:216)
        at android.app.ActivityThread.main(ActivityThread.java:7586)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1034)
     Caused by: java.lang.SecurityException: getPackageUid: Neither user 10121 nor current process has android.permission.INTERACT_ACROSS_USERS.
        at android.os.Parcel.createException(Parcel.java:1953)
        at android.os.Parcel.readException(Parcel.java:1921)
        at android.os.Parcel.readException(Parcel.java:1871)
        at android.net.IConnectivityManager$Stub$Proxy.establishVpn(IConnectivityManager.java:1996)
        at android.net.VpnService$Builder.establish(VpnService.java:820)
        at io.github.trojan_gfw.igniter.ProxyService.onStartCommand(ProxyService.java:322)
        at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4316)
        at android.app.ActivityThread.access$2700(ActivityThread.java:259) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2079) 
        at android.os.Handler.dispatchMessage(Handler.java:112) 
        at android.os.Looper.loop(Looper.java:216) 
        at android.app.ActivityThread.main(ActivityThread.java:7586) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1034) 
     Caused by: android.os.RemoteException: Remote stack trace:
        at android.app.ContextImpl.enforce(Ljava/lang/String;IZILjava/lang/String;)V(libmapleframework.so:3872781)
        at android.app.ContextImpl.enforceCallingOrSelfPermission(Ljava/lang/String;Ljava/lang/String;)V(libmapleframework.so:4351001)
        at com.android.server.pm.permission.PermissionManagerService.enforceCrossUserPermission(IIZZZLjava/lang/String;)V(libmapleservices.so:2971893)
        at com.android.server.pm.PackageManagerService.getPackageUid(Ljava/lang/String;II)I(libmapleservices.so:3050209)
        at huawei.android.app.HwApiCacheMangerEx.getPackageUidAsUser(Landroid/content/pm/IPackageManager;Ljava/lang/String;II)I(libmaplehwEmui.so:665593)

**Comment by defghy** [comment]
`2020-06-08 09:51:59.401 13265-13265/? E/w.igniter:prox: [qarth_debug:]  get PatchStore::createDisableExceptionQarthFile method fail.
    
    --------- beginning of crash
2020-06-08 09:51:59.402 13265-13265/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: io.github.trojan_gfw.igniter:proxy, PID: 13265
    java.lang.RuntimeException: Unable to start service io.github.trojan_gfw.igniter.ProxyService@770844a with Intent { cmp=io.github.trojan_gfw.igniter/.ProxyService (has extras) }: java.lang.SecurityException: getPackageUid: Neither user 10121 nor current process has android.permission.INTERACT_ACROSS_USERS.
        at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4337)
        at android.app.ActivityThread.access$2700(ActivityThread.java:259)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2079)
        at android.os.Handler.dispatchMessage(Handler.java:112)
        at android.os.Looper.loop(Looper.java:216)
        at android.app.ActivityThread.main(ActivityThread.java:7586)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1034)
     Caused by: java.lang.SecurityException: getPackageUid: Neither user 10121 nor current process has android.permission.INTERACT_ACROSS_USERS.
        at android.os.Parcel.createException(Parcel.java:1953)
        at android.os.Parcel.readException(Parcel.java:1921)
        at android.os.Parcel.readException(Parcel.java:1871)
        at android.net.IConnectivityManager$Stub$Proxy.establishVpn(IConnectivityManager.java:1996)
        at android.net.VpnService$Builder.establish(VpnService.java:820)
        at io.github.trojan_gfw.igniter.ProxyService.onStartCommand(ProxyService.java:322)
        at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4316)
        at android.app.ActivityThread.access$2700(ActivityThread.java:259) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2079) 
        at android.os.Handler.dispatchMessage(Handler.java:112) 
        at android.os.Looper.loop(Looper.java:216) 
        at android.app.ActivityThread.main(ActivityThread.java:7586) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1034) 
     Caused by: android.os.RemoteException: Remote stack trace:
        at android.app.ContextImpl.enforce(Ljava/lang/String;IZILjava/lang/String;)V(libmapleframework.so:3872781)
        at android.app.ContextImpl.enforceCallingOrSelfPermission(Ljava/lang/String;Ljava/lang/String;)V(libmapleframework.so:4351001)
        at com.android.server.pm.permission.PermissionManagerService.enforceCrossUserPermission(IIZZZLjava/lang/String;)V(libmapleservices.so:2971893)
        at com.android.server.pm.PackageManagerService.getPackageUid(Ljava/lang/String;II)I(libmapleservices.so:3050209)
        at huawei.android.app.HwApiCacheMangerEx.getPackageUidAsUser(Landroid/content/pm/IPackageManager;Ljava/lang/String;II)I(libmaplehwEmui.so:665593)
2020-06-08 09:52:00.450 13331-13331/? E/w.igniter:prox: Not starting debugger since process cannot load the jdwp agent.
2020-06-08 09:52:00.530 1197-1197/? E/NotificationService: Muting recently noisy 0|io.github.trojan_gfw.igniter|114514|null|10121
2020-06-08 09:52:00.593 13331-13331/? E/w.igniter:prox: [qarth_debug:]  get PatchStore::createDisableExceptionQarthFile method fail.
2020-06-08 09:52:00.594 13331-13331/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: io.github.trojan_gfw.igniter:proxy, PID: 13331
    java.lang.RuntimeException: Unable to start service io.github.trojan_gfw.igniter.ProxyService@770844a with Intent { cmp=io.github.trojan_gfw.igniter/.ProxyService (has extras) }: java.lang.SecurityException: getPackageUid: Neither user 10121 nor current process has android.permission.INTERACT_ACROSS_USERS.
        at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4337)
        at android.app.ActivityThread.access$2700(ActivityThread.java:259)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2079)
        at android.os.Handler.dispatchMessage(Handler.java:112)
        at android.os.Looper.loop(Looper.java:216)
        at android.app.ActivityThread.main(ActivityThread.java:7586)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1034)
     Caused by: java.lang.SecurityException: getPackageUid: Neither user 10121 nor current process has android.permission.INTERACT_ACROSS_USERS.
        at android.os.Parcel.createException(Parcel.java:1953)
        at android.os.Parcel.readException(Parcel.java:1921)
        at android.os.Parcel.readException(Parcel.java:1871)
        at android.net.IConnectivityManager$Stub$Proxy.establishVpn(IConnectivityManager.java:1996)
        at android.net.VpnService$Builder.establish(VpnService.java:820)
        at io.github.trojan_gfw.igniter.ProxyService.onStartCommand(ProxyService.java:322)
        at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4316)
        at android.app.ActivityThread.access$2700(ActivityThread.java:259) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2079) 
        at android.os.Handler.dispatchMessage(Handler.java:112) 
        at android.os.Looper.loop(Looper.java:216) 
        at android.app.ActivityThread.main(ActivityThread.java:7586) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1034) 
     Caused by: android.os.RemoteException: Remote stack trace:
        at android.app.ContextImpl.enforce(Ljava/lang/String;IZILjava/lang/String;)V(libmapleframework.so:3872781)
        at android.app.ContextImpl.enforceCallingOrSelfPermission(Ljava/lang/String;Ljava/lang/String;)V(libmapleframework.so:4351001)
        at com.android.server.pm.permission.PermissionManagerService.enforceCrossUserPermission(IIZZZLjava/lang/String;)V(libmapleservices.so:2971893)
        at com.android.server.pm.PackageManagerService.getPackageUid(Ljava/lang/String;II)I(libmapleservices.so:3050209)
        at huawei.android.app.HwApiCacheMangerEx.getPackageUidAsUser(Landroid/content/pm/IPackageManager;Ljava/lang/String;II)I(libmaplehwEmui.so:665593)
2020-06-08 09:52:01.642 13370-13370/? E/w.igniter:prox: Not starting debugger since process cannot load the jdwp agent.
2020-06-08 09:52:01.735 1197-1197/? E/NotificationService: Muting recently noisy 0|io.github.trojan_gfw.igniter|114514|null|10121
2020-06-08 09:52:01.812 13370-13370/? E/w.igniter:prox: [qarth_debug:]  get PatchStore::createDisableExceptionQarthFile method fail.
2020-06-08 09:52:01.813 13370-13370/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: io.github.trojan_gfw.igniter:proxy, PID: 13370
    java.lang.RuntimeException: Unable to start service io.github.trojan_gfw.igniter.ProxyService@770844a with Intent { cmp=io.github.trojan_gfw.igniter/.ProxyService (has extras) }: java.lang.SecurityException: getPackageUid: Neither user 10121 nor current process has android.permission.INTERACT_ACROSS_USERS.
        at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4337)
        at android.app.ActivityThread.access$2700(ActivityThread.java:259)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2079)
        at android.os.Handler.dispatchMessage(Handler.java:112)
        at android.os.Looper.loop(Looper.java:216)
        at android.app.ActivityThread.main(ActivityThread.java:7586)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1034)
     Caused by: java.lang.SecurityException: getPackageUid: Neither user 10121 nor current process has android.permission.INTERACT_ACROSS_USERS.
        at android.os.Parcel.createException(Parcel.java:1953)
        at android.os.Parcel.readException(Parcel.java:1921)
        at android.os.Parcel.readException(Parcel.java:1871)
        at android.net.IConnectivityManager$Stub$Proxy.establishVpn(IConnectivityManager.java:1996)
        at android.net.VpnService$Builder.establish(VpnService.java:820)
        at io.github.trojan_gfw.igniter.ProxyService.onStartCommand(ProxyService.java:322)
        at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4316)
        at android.app.ActivityThread.access$2700(ActivityThread.java:259) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2079) 
        at android.os.Handler.dispatchMessage(Handler.java:112) 
        at android.os.Looper.loop(Looper.java:216) 
        at android.app.ActivityThread.main(ActivityThread.java:7586) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1034) 
     Caused by: android.os.RemoteException: Remote stack trace:
        at android.app.ContextImpl.enforce(Ljava/lang/String;IZILjava/lang/String;)V(libmapleframework.so:3872781)
        at android.app.ContextImpl.enforceCallingOrSelfPermission(Ljava/lang/String;Ljava/lang/String;)V(libmapleframework.so:4351001)
        at com.android.server.pm.permission.PermissionManagerService.enforceCrossUserPermission(IIZZZLjava/lang/String;)V(libmapleservices.so:2971893)
        at com.android.server.pm.PackageManagerService.getPackageUid(Ljava/lang/String;II)I(libmapleservices.so:3050209)
        at huawei.android.app.HwApiCacheMangerEx.getPackageUidAsUser(Landroid/content/pm/IPackageManager;Ljava/lang/String;II)I(libmaplehwEmui.so:665593)
`

**Comment by defghy** [comment]
`
2020-06-08 09:51:59.401 13265-13265/? E/w.igniter:prox: [qarth_debug:]  get PatchStore::createDisableExceptionQarthFile method fail.
    
    --------- beginning of crash
2020-06-08 09:51:59.402 13265-13265/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: io.github.trojan_gfw.igniter:proxy, PID: 13265
    java.lang.RuntimeException: Unable to start service io.github.trojan_gfw.igniter.ProxyService@770844a with Intent { cmp=io.github.trojan_gfw.igniter/.ProxyService (has extras) }: java.lang.SecurityException: getPackageUid: Neither user 10121 nor current process has android.permission.INTERACT_ACROSS_USERS.
        at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4337)
        at android.app.ActivityThread.access$2700(ActivityThread.java:259)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2079)
        at android.os.Handler.dispatchMessage(Handler.java:112)
        at android.os.Looper.loop(Looper.java:216)
        at android.app.ActivityThread.main(ActivityThread.java:7586)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1034)
     Caused by: java.lang.SecurityException: getPackageUid: Neither user 10121 nor current process has android.permission.INTERACT_ACROSS_USERS.
        at android.os.Parcel.createException(Parcel.java:1953)
        at android.os.Parcel.readException(Parcel.java:1921)
        at android.os.Parcel.readException(Parcel.java:1871)
        at android.net.IConnectivityManager$Stub$Proxy.establishVpn(IConnectivityManager.java:1996)
        at android.net.VpnService$Builder.establish(VpnService.java:820)
        at io.github.trojan_gfw.igniter.ProxyService.onStartCommand(ProxyService.java:322)
        at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4316)
        at android.app.ActivityThread.access$2700(ActivityThread.java:259) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2079) 
        at android.os.Handler.dispatchMessage(Handler.java:112) 
        at android.os.Looper.loop(Looper.java:216) 
        at android.app.ActivityThread.main(ActivityThread.java:7586) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1034) 
     Caused by: android.os.RemoteException: Remote stack trace:
        at android.app.ContextImpl.enforce(Ljava/lang/String;IZILjava/lang/String;)V(libmapleframework.so:3872781)
        at android.app.ContextImpl.enforceCallingOrSelfPermission(Ljava/lang/String;Ljava/lang/String;)V(libmapleframework.so:4351001)
        at com.android.server.pm.permission.PermissionManagerService.enforceCrossUserPermission(IIZZZLjava/lang/String;)V(libmapleservices.so:2971893)
        at com.android.server.pm.PackageManagerService.getPackageUid(Ljava/lang/String;II)I(libmapleservices.so:3050209)
        at huawei.android.app.HwApiCacheMangerEx.getPackageUidAsUser(Landroid/content/pm/IPackageManager;Ljava/lang/String;II)I(libmaplehwEmui.so:665593)
2020-06-08 09:52:00.450 13331-13331/? E/w.igniter:prox: Not starting debugger since process cannot load the jdwp agent.
2020-06-08 09:52:00.530 1197-1197/? E/NotificationService: Muting recently noisy 0|io.github.trojan_gfw.igniter|114514|null|10121
2020-06-08 09:52:00.593 13331-13331/? E/w.igniter:prox: [qarth_debug:]  get PatchStore::createDisableExceptionQarthFile method fail.
2020-06-08 09:52:00.594 13331-13331/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: io.github.trojan_gfw.igniter:proxy, PID: 13331
    java.lang.RuntimeException: Unable to start service io.github.trojan_gfw.igniter.ProxyService@770844a with Intent { cmp=io.github.trojan_gfw.igniter/.ProxyService (has extras) }: java.lang.SecurityException: getPackageUid: Neither user 10121 nor current process has android.permission.INTERACT_ACROSS_USERS.
        at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4337)
        at android.app.ActivityThread.access$2700(ActivityThread.java:259)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2079)
        at android.os.Handler.dispatchMessage(Handler.java:112)
        at android.os.Looper.loop(Looper.java:216)
        at android.app.ActivityThread.main(ActivityThread.java:7586)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1034)
     Caused by: java.lang.SecurityException: getPackageUid: Neither user 10121 nor current process has android.permission.INTERACT_ACROSS_USERS.
        at android.os.Parcel.createException(Parcel.java:1953)
        at android.os.Parcel.readException(Parcel.java:1921)
        at android.os.Parcel.readException(Parcel.java:1871)
        at android.net.IConnectivityManager$Stub$Proxy.establishVpn(IConnectivityManager.java:1996)
        at android.net.VpnService$Builder.establish(VpnService.java:820)
        at io.github.trojan_gfw.igniter.ProxyService.onStartCommand(ProxyService.java:322)
        at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4316)
        at android.app.ActivityThread.access$2700(ActivityThread.java:259) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2079) 
        at android.os.Handler.dispatchMessage(Handler.java:112) 
        at android.os.Looper.loop(Looper.java:216) 
        at android.app.ActivityThread.main(ActivityThread.java:7586) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1034) 
     Caused by: android.os.RemoteException: Remote stack trace:
        at android.app.ContextImpl.enforce(Ljava/lang/String;IZILjava/lang/String;)V(libmapleframework.so:3872781)
        at android.app.ContextImpl.enforceCallingOrSelfPermission(Ljava/lang/String;Ljava/lang/String;)V(libmapleframework.so:4351001)
        at com.android.server.pm.permission.PermissionManagerService.enforceCrossUserPermission(IIZZZLjava/lang/String;)V(libmapleservices.so:2971893)
        at com.android.server.pm.PackageManagerService.getPackageUid(Ljava/lang/String;II)I(libmapleservices.so:3050209)
        at huawei.android.app.HwApiCacheMangerEx.getPackageUidAsUser(Landroid/content/pm/IPackageManager;Ljava/lang/String;II)I(libmaplehwEmui.so:665593)
2020-06-08 09:52:01.642 13370-13370/? E/w.igniter:prox: Not starting debugger since process cannot load the jdwp agent.
2020-06-08 09:52:01.735 1197-1197/? E/NotificationService: Muting recently noisy 0|io.github.trojan_gfw.igniter|114514|null|10121
2020-06-08 09:52:01.812 13370-13370/? E/w.igniter:prox: [qarth_debug:]  get PatchStore::createDisableExceptionQarthFile method fail.
2020-06-08 09:52:01.813 13370-13370/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: io.github.trojan_gfw.igniter:proxy, PID: 13370
    java.lang.RuntimeException: Unable to start service io.github.trojan_gfw.igniter.ProxyService@770844a with Intent { cmp=io.github.trojan_gfw.igniter/.ProxyService (has extras) }: java.lang.SecurityException: getPackageUid: Neither user 10121 nor current process has android.permission.INTERACT_ACROSS_USERS.
        at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4337)
        at android.app.ActivityThread.access$2700(ActivityThread.java:259)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2079)
        at android.os.Handler.dispatchMessage(Handler.java:112)
        at android.os.Looper.loop(Looper.java:216)
        at android.app.ActivityThread.main(ActivityThread.java:7586)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1034)
     Caused by: java.lang.SecurityException: getPackageUid: Neither user 10121 nor current process has android.permission.INTERACT_ACROSS_USERS.
        at android.os.Parcel.createException(Parcel.java:1953)
        at android.os.Parcel.readException(Parcel.java:1921)
        at android.os.Parcel.readException(Parcel.java:1871)
        at android.net.IConnectivityManager$Stub$Proxy.establishVpn(IConnectivityManager.java:1996)
        at android.net.VpnService$Builder.establish(VpnService.java:820)
        at io.github.trojan_gfw.igniter.ProxyService.onStartCommand(ProxyService.java:322)
        at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4316)
        at android.app.ActivityThread.access$2700(ActivityThread.java:259) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2079) 
        at android.os.Handler.dispatchMessage(Handler.java:112) 
        at android.os.Looper.loop(Looper.java:216) 
        at android.app.ActivityThread.main(ActivityThread.java:7586) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1034) 
     Caused by: android.os.RemoteException: Remote stack trace:
        at android.app.ContextImpl.enforce(Ljava/lang/String;IZILjava/lang/String;)V(libmapleframework.so:3872781)
        at android.app.ContextImpl.enforceCallingOrSelfPermission(Ljava/lang/String;Ljava/lang/String;)V(libmapleframework.so:4351001)
        at com.android.server.pm.permission.PermissionManagerService.enforceCrossUserPermission(IIZZZLjava/lang/String;)V(libmapleservices.so:2971893)
        at com.android.server.pm.PackageManagerService.getPackageUid(Ljava/lang/String;II)I(libmapleservices.so:3050209)
        at huawei.android.app.HwApiCacheMangerEx.getPackageUidAsUser(Landroid/content/pm/IPackageManager;Ljava/lang/String;II)I(libmaplehwEmui.so:665593)

`
