### ISSUE TITLE
Crash on Android 5.0

### ISSUE THREAD

**Issue by mengmo** [trojan-gfw/igniter#95]
在 Android 7.1.1 上运行正常
Android 5.0 上闪退的原因可能如下
```
D/ResourcesManager( 1193): creating new AssetManager and set to /data/app/io.github.trojan_gfw.igniter-2/base.apk
W/ResourceType( 1193): Failure getting entry for 0x7f070056 (t=6 e=86) (error -75)
I/Choreographer( 7747): Skipped 33 frames!  The application may be doing too much work on its main thread.
W/ContextImpl( 1037): Calling a method in the system process without a qualified user: android.app.ContextImpl.sendBroadcast:1699 com.android.server.InputMethodManagerService$6.run:2733 java.lang.Thread.run:818 <bottom of call stack> <bottom of call stack>
W/StatusBarIconView( 1193): Icon not found in 2131165270: 7f070056
W/StatusBarIconView( 1193): No icon for slot io.github.trojan_gfw.igniter/0x0
W/StatusBar( 1193): removeNotification for unknown key: 0|io.github.trojan_gfw.igniter|0|null|10507
D/NotificationService( 1037): onNotification error pkg=io.github.trojan_gfw.igniter tag=null id=0; will crashApplication(uid=10507, pid=7747)

W/StatusBar( 1193): removeNotification for unknown key: 0|io.github.trojan_gfw.igniter|0|null|10507
D/AndroidRuntime( 7747): Shutting down VM
E/AndroidRuntime( 7747): FATAL EXCEPTION: main
E/AndroidRuntime( 7747): Process: io.github.trojan_gfw.igniter, PID: 7747
E/AndroidRuntime( 7747): android.app.RemoteServiceException: Bad notification posted from package io.github.trojan_gfw.igniter: Couldn't create icon: StatusBarIcon(pkg=io.github.trojan_gfw.igniteruser=0 id=0x7f070056 level=0 visible=true num=0 )
E/AndroidRuntime( 7747):        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1622)
E/AndroidRuntime( 7747):        at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime( 7747):        at android.os.Looper.loop(Looper.java:145)
E/AndroidRuntime( 7747):        at android.app.ActivityThread.main(ActivityThread.java:5942)
E/AndroidRuntime( 7747):        at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 7747):        at java.lang.reflect.Method.invoke(Method.java:372)
E/AndroidRuntime( 7747):        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1400)
E/AndroidRuntime( 7747):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1195)
V/ApplicationPolicy( 1037): isApplicationStateBlocked userId 0 pkgname io.github.trojan_gfw.igniter
W/ActivityManager( 1037):   Force finishing activity io.github.trojan_gfw.igniter/.MainActivity
```

**Comment by GreaterFire** [comment]
`Bad notification posted from package io.github.trojan_gfw.igniter: Couldn't create icon: StatusBarIcon`

**Comment by wongsyrone** [comment]
Might be caused by `R.drawable.ic_launcher_foreground` is missing for Android 5.0. I don't know how to draw such images, I appreciate it if someone helps.

ref:
https://github.com/trojan-gfw/igniter/tree/master/app/src/main/res/drawable
https://github.com/trojan-gfw/igniter/tree/master/app/src/main/res/drawable-v24

**Comment by fuzhengqu** [comment]
My android6.0.1 phone cannot run this app，I think the problem is the same as @mengmo ‘s situation. But I found that some old versions can work normally, such as 0.1.0-pre-alpha13，Or you tell me how to collect crash  logs

**Comment by wongsyrone** [comment]
Please try commit: https://github.com/trojan-gfw/igniter/commit/7aaa1d045714576df746e455f5c487a3ee428327
